main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
    # route for pokemon index
  path('pokemon/', views.pokemon_index, name='index'),
  path('pokemon/<int:poke_id>/', views.pokemon_detail, name='detail'),
    # new route used to show a form and create a pokemon
  path('pokemon/create/', views.PokeCreate.as_view(), name='pokemon_create'),
  path('pokemon/<int:pk>/update/', views.PokeUpdate.as_view(), name='pokemon_update'),
  path('pokemon/<int:pk>/delete/', views.PokeDelete.as_view(), name='pokemon_delete'),
  path('pokemon/<int:poke_id>/add_training/', views.add_training, name='add_training'),
]

pokemoncollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')), # set up main app url
]

main_app/models.py
from django.db import models
# Import the reverse function
from django.urls import reverse

# Create your models here.
class Poke(models.Model):
	name = models.CharField(max_length=100)
	element = models.CharField(max_length=100)
	attack = models.CharField(max_length=250)
	hp = models.IntegerField()


	def __str__(self):
		return f"The pokemon named {self.name} has id of {self.id}"

	#method
	def get_absolute_url(self):
		return reverse('detail', kwargs={'poke_id': self.id})


FIGHTS = (
    ('B', 'Beginner'),
    ('I', 'Intermediate'),
    ('E', 'Expert'),
)

class Training(models.Model):
    date = models.DateField('training date')
    fight = models.CharField(
	    max_length=1,	
	    choices=FIGHTS,
	    default=FIGHTS[0][0]
	)

    poke = models.ForeignKey(Poke, on_delete=models.CASCADE)

def __str__(self):
	return f"{self.get_fight_display()} on {self.date}"

class Meta:
	ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Training

class TrainingForm(ModelForm):
    class Meta:
        model = Training
        fields = ['date', 'fight']

main_app/views.py
from django.shortcuts import render, redirect
#import the create view class
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Add the following import
from django.http import HttpResponse
from .models import Poke 
from .forms import TrainingForm
# the template the create view and the update view use is the same 
#templates /<appname
class PokeCreate(CreateView):
    model = Poke
    fields = '__all__'


class PokeUpdate(UpdateView):
    model = Poke
    # Let's disallow the renaming of a cat by excluding the name field!
    fields = ['element', 'attack', 'hp']

class PokeDelete(DeleteView):
    model = Poke
    success_url = '/pokemon/'

# Define the home view
def home(request):
    return HttpResponse('<h1>Hello /ᐠ｡‸｡ᐟ\ﾉ</h1>')


def about(request):
    return render(request, 'about.html')

def pokemon_index(request):
    pokemon = Poke.objects.all()
    return render(request, 'pokemon/index.html', {'pokemon': pokemon})

def pokemon_detail(request, poke_id):
    poke = Poke.objects.get(id=poke_id)
    training_form = TrainingForm()
    
    return render(request, 'pokemon/detail.html', {
    'poke': poke, 'training_form': training_form 
    })

def add_training(request, poke_id):

    #create a model form instance using the data in the request 
    form = TrainingForm(request.POST)
    #validate
    if form.is_valid():
        #do something
        new_training = form.save(commit=False)
        new_training.poke_id = poke_id
        new_training.save()

    return redirect('detail', poke_id=poke_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Pokemon Collector</h1>
<hr />
<p>Hire the Pokemon Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Pokemon Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;PokemonCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
<!-- new link below -->
          <li><a href="{% url 'pokemon_create' %}">Add a Pokemon</a></li>
          <li><a href="{% url 'index' %}">View All My Pokemon</a></li>
        </ul> 
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Pokemon Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/main_app/poke_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Pokemon</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' poke.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/poke_form.html
{% extends 'base.html' %}

{% block content %}
  <!-- New if/else block -->
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Pokemon</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/pokemon_form.html
{% extends 'base.html' %}

{% block content %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/pokemon/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Pokemon Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ poke.name }}</span>
        <p>Element: {{ poke.element }}</p>
        <p>Attack: {{ poke.attack }}</p>
      {% if poke.hp > 0 %}
      <p>HP: {{ poke.hp }}</p>
      {% else %}
      <p>HP: low level</p>
      {% endif %}
    </div>
  <div class="card-action">
    <a href="{% url 'pokemon_update' poke.id %}">Edit</a>
    <a href="{% url 'pokemon_delete' poke.id %}">Delete</a>
    </div>
  </div>
</div>
<div class="col s6">
  <form method="post" action="{% url 'add_training' poke.id %}">
    {% csrf_token %}
    {{ training_form.as_p }}
    <input type="submit" class="btn" value="Add Training">
</form>
<table class="striped">
  <thead>
    <tr><th>Date</th><th>Fight</th></tr>
  </thead>
  <tbody>
    {% for training in poke.training_set.all %}
      <tr>
        <td>{{training.date}}</td>
        <td>{{training.get_fight_display}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
</div>
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  })

  const selectEl = document.getElementById('id_fight');
  M.FormSelect.init(selectEl);



</script>
{% endblock %}

main_app/templates/pokemon/index.html
{% extends 'base.html' %}

{% block content %}

<h1> Pokedex </h1>

{% for poke in pokemon %}
<a href="{% url 'detail' poke.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ poke.name }}</span>
      <p>Element: {{ poke.element }}</p>
      <p>Attack: {{ poke.attack}}</p>
      {% if poke.hp > 0 %}
        <p>HP: {{ poke.hp}}</p>
      {% else %}
        <p>hp: Low level</p>
      {% endif %}
    </div>
  </div>

{% endfor %}

{% endblock %}